# ============================================================
# sk-keys Restructuring Script — v1.0
# Creates all category index.md files
# ============================================================
$base = "C:\ASK\MyWorkspace\sk-keys"
$docs = "$base\docs"
function Write-Index($folder, $title, $slug, $navOrder, $range, $count, $desc, $keywords) {
    $path = "$docs\$folder\index.md"
    $rows = ($keywords | ForEach-Object { "| $_[0] | $_[1] | $_[2] |" }) -join "`n"
    $content = @"
---
layout: default
title: "$title"
parent: "Documentation"
nav_order: $navOrder
has_children: true
permalink: /$slug/
---
# $title
$desc
**Keywords:** $range ($count terms)
| # | Keyword | Difficulty |
|---|---|---|
$rows
"@
    [System.IO.File]::WriteAllText($path, $content, [System.Text.UTF8Encoding]::new($false))
    Write-Host "Written: $folder\index.md"
}
# ── 01 CS Fundamentals (001-030) ──────────────────────────
Write-Index "CS Fundamentals" "CS Fundamentals — Paradigms & Theory" "cs-fundamentals" 1 "001–030" "30 terms" "Programming paradigms, type systems, OOP pillars, functional concepts, and theoretical foundations." @(
    @("001","Imperative Programming","★☆☆"),@("002","Declarative Programming","★☆☆"),@("003","Object-Oriented Programming (OOP)","★☆☆"),@("004","Functional Programming","★★☆"),@("005","Procedural Programming","★☆☆"),@("006","Event-Driven Programming","★★☆"),@("007","Reactive Programming","★★☆"),@("008","Aspect-Oriented Programming","★★☆"),@("009","Metaprogramming","★★★"),@("010","Type Systems (Static vs Dynamic)","★★☆"),@("011","Strong vs Weak Typing","★☆☆"),@("012","Compiled vs Interpreted Languages","★☆☆"),@("013","Memory Management Models","★★☆"),@("014","Concurrency vs Parallelism","★★☆"),@("015","Synchronous vs Asynchronous","★☆☆"),@("016","Abstraction","★☆☆"),@("017","Encapsulation","★☆☆"),@("018","Polymorphism","★☆☆"),@("019","Inheritance","★☆☆"),@("020","Composition over Inheritance","★★☆"),@("021","Recursion","★★☆"),@("022","Tail Recursion","★★★"),@("023","Turing Completeness","★★★"),@("024","Church-Turing Thesis","★★★"),@("025","Lambda Calculus","★★★"),@("026","First-Class Functions","★★☆"),@("027","Higher-Order Functions","★★☆"),@("028","Side Effects","★★☆"),@("029","Referential Transparency","★★★"),@("030","Idempotency","★★☆"))
# ── 02 DSA (031-090) ─────────────────────────────────────
Write-Index "DSA" "Data Structures & Algorithms" "dsa" 2 "031–090" "60 terms" "Core data structures, algorithm design paradigms, complexity analysis, sorting, and graph algorithms." @(
    @("031","Array","★☆☆"),@("032","LinkedList","★☆☆"),@("033","Stack","★☆☆"),@("034","Queue / Deque","★☆☆"),@("035","HashMap","★☆☆"),@("036","TreeMap","★★☆"),@("037","Heap (Min/Max)","★★☆"),@("038","Priority Queue","★★☆"),@("039","Trie","★★☆"),@("040","Graph","★★☆"),@("041","Segment Tree","★★★"),@("042","Fenwick Tree (BIT)","★★★"),@("043","Skip List","★★★"),@("044","Bloom Filter","★★★"),@("045","Consistent Hash Ring","★★★"),@("046","LRU Cache","★★☆"),@("047","LFU Cache","★★★"),@("048","Time Complexity / Big-O","★★☆"),@("049","Space Complexity","★★☆"),@("050","Amortized Analysis","★★★"),@("051","Memoization","★★☆"),@("052","Tabulation (Bottom-Up DP)","★★☆"),@("053","Divide and Conquer","★★☆"),@("054","Greedy Algorithm","★★☆"),@("055","Dynamic Programming","★★★"),@("056","BFS","★★☆"),@("057","DFS","★★☆"),@("058","Topological Sort","★★☆"),@("059","Dijkstra","★★☆"),@("060","Bellman-Ford","★★★"),@("061","A* Search","★★★"),@("062","Union-Find (Disjoint Set)","★★☆"),@("063","Kruskal / Prim","★★★"),@("064","Quicksort","★★☆"),@("065","Mergesort","★★☆"),@("066","Timsort","★★★"),@("067","Heapsort","★★★"),@("068","Radix Sort","★★★"),@("069","Two Pointer","★★☆"),@("070","Sliding Window","★★☆"),@("071","Binary Search","★★☆"),@("072","Backtracking","★★☆"),@("073","Bit Manipulation","★★★"),@("074","String Matching (KMP, Rabin-Karp)","★★★"),@("075","Hashing Techniques","★★☆"),@("076","Graph Coloring","★★★"),@("077","Minimum Spanning Tree","★★★"),@("078","Strongly Connected Components","★★★"),@("079","Longest Common Subsequence","★★★"),@("080","Knapsack Problem","★★★"),@("081","NP-Complete Problems","★★★"),@("082","P vs NP","★★★"),@("083","Complexity Classes","★★★"),@("084","Space-Time Trade-off","★★☆"),@("085","Randomized Algorithms","★★★"),@("086","Approximation Algorithms","★★★"),@("087","Monte Carlo vs Las Vegas Algorithms","★★★"),@("088","Sorting Stability","★★☆"),@("089","In-Place vs Out-of-Place","★★☆"),@("090","Recursion vs Iteration Trade-offs","★★☆"))
# ── 03 Operating Systems (091-125) ───────────────────────
Write-Index "Operating Systems" "Operating Systems" "operating-systems" 3 "091–125" "35 terms" "Processes, threads, memory management, I/O models, synchronization primitives, and OS internals." @(
    @("091","Process","★☆☆"),@("092","Thread","★☆☆"),@("093","Fiber / Coroutine","★★☆"),@("094","Process vs Thread","★☆☆"),@("095","Context Switch","★★☆"),@("096","Scheduler / Preemption","★★☆"),@("097","User Space vs Kernel Space","★★☆"),@("098","System Call (syscall)","★★☆"),@("099","Virtual Memory","★★☆"),@("100","Paging","★★☆"),@("101","Page Fault","★★☆"),@("102","TLB (Translation Lookaside Buffer)","★★★"),@("103","Memory-Mapped File (mmap)","★★★"),@("104","Blocking I/O","★★☆"),@("105","Non-Blocking I/O","★★☆"),@("106","Async I/O","★★☆"),@("107","epoll / kqueue / io_uring","★★★"),@("108","File Descriptor","★★☆"),@("109","Page Cache","★★★"),@("110","Zero-Copy (sendfile)","★★★"),@("111","NUMA","★★★"),@("112","Cache Line","★★★"),@("113","False Sharing","★★★"),@("114","Mutex","★★☆"),@("115","Semaphore","★★☆"),@("116","Spinlock","★★★"),@("117","Condition Variable","★★☆"),@("118","Deadlock","★★☆"),@("119","Livelock","★★★"),@("120","Starvation","★★☆"),@("121","Fork / Exec","★★☆"),@("122","Signal Handling","★★★"),@("123","Inode / File System","★★☆"),@("124","Swap / Thrashing","★★★"),@("125","Buddy System / Slab Allocator","★★★"))
# ── 04 Linux (126-165) ────────────────────────────────────
Write-Index "Linux" "Linux" "linux" 4 "126–165" "40 terms" "Linux filesystem, shell scripting, process management, networking tools, performance tuning, and security." @(
    @("126","Linux File System Hierarchy","★☆☆"),@("127","File Permissions (chmod, chown)","★☆☆"),@("128","Users and Groups","★☆☆"),@("129","Shell (bash, zsh)","★☆☆"),@("130","Shell Scripting","★★☆"),@("131","stdin / stdout / stderr","★☆☆"),@("132","Pipes and Redirection","★☆☆"),@("133","Process Management (ps, top, kill)","★☆☆"),@("134","Systemd / Init System","★★☆"),@("135","Cron Jobs","★☆☆"),@("136","Environment Variables (Linux)","★☆☆"),@("137","Package Managers (apt, yum, dnf)","★☆☆"),@("138","SSH","★☆☆"),@("139","SCP / rsync","★☆☆"),@("140","curl / wget","★☆☆"),@("141","grep / awk / sed","★★☆"),@("142","find / xargs","★★☆"),@("143","tar / gzip / zip","★☆☆"),@("144","Symbolic Links / Hard Links","★★☆"),@("145","/proc File System","★★★"),@("146","/sys File System","★★★"),@("147","Linux Networking (ip, ss, netstat)","★★☆"),@("148","iptables / nftables","★★★"),@("149","tcpdump / Wireshark","★★★"),@("150","strace / ltrace","★★★"),@("151","lsof","★★☆"),@("152","ulimit","★★★"),@("153","swap Management","★★☆"),@("154","Memory (free, vmstat)","★★☆"),@("155","Disk I/O (iostat, iotop)","★★☆"),@("156","Kernel Modules","★★★"),@("157","Linux Namespaces","★★★"),@("158","Cgroups","★★★"),@("159","SELinux / AppArmor","★★★"),@("160","Linux Security Hardening","★★★"),@("161","Signals (SIGTERM, SIGKILL, SIGHUP)","★★☆"),@("162","Zombie Processes","★★☆"),@("163","/etc/hosts / DNS Resolution","★★☆"),@("164","tmux / screen","★☆☆"),@("165","Linux Performance Tuning","★★★"))
# ── 05 Networking (166-205) ───────────────────────────────
Write-Index "Networking" "Networking" "networking" 5 "166–205" "40 terms" "OSI model, TCP/IP, protocols, DNS, load balancing, security, and network observability." @(
    @("166","OSI Model (7 Layers)","★☆☆"),@("167","TCP/IP Stack","★☆☆"),@("168","TCP","★★☆"),@("169","UDP","★★☆"),@("170","QUIC","★★★"),@("171","TCP Handshake (3-Way)","★★☆"),@("172","TCP Teardown","★★☆"),@("173","Congestion Control","★★★"),@("174","Flow Control","★★★"),@("175","Sliding Window","★★★"),@("176","IP Addressing","★☆☆"),@("177","Subnet / CIDR","★★☆"),@("178","NAT","★★☆"),@("179","DNS","★☆☆"),@("180","DNS Resolution Flow","★★☆"),@("181","CDN","★★☆"),@("182","Anycast","★★★"),@("183","Socket / Port / Ephemeral Port","★★☆"),@("184","Firewall","★★☆"),@("185","VPN","★★☆"),@("186","Proxy vs Reverse Proxy","★★☆"),@("187","Load Balancer (L4 vs L7)","★★☆"),@("188","Packet Loss / Latency / Jitter","★★☆"),@("189","Bandwidth vs Throughput","★★☆"),@("190","Network Latency Optimization","★★★"),@("191","BGP","★★★"),@("192","DHCP","★☆☆"),@("193","ARP","★★☆"),@("194","ICMP / ping / traceroute","★☆☆"),@("195","Network Topologies","★☆☆"),@("196","Zero Trust Networking","★★★"),@("197","East-West vs North-South Traffic","★★★"),@("198","Service Discovery (Network)","★★★"),@("199","Network Policies","★★★"),@("200","Overlay Networks","★★★"),@("201","VLAN","★★★"),@("202","mTLS","★★★"),@("203","TLS/SSL","★★☆"),@("204","Certificate Authority (CA)","★★☆"),@("205","Network Observability","★★★"))
# ── 06 HTTP & APIs (206-260) ──────────────────────────────
Write-Index "HTTP & APIs" "HTTP & APIs" "http-apis" 6 "206–260" "55 terms" "HTTP versions, REST, GraphQL, gRPC, WebSocket, API security, authentication, and API design best practices." @(
    @("206","HTTP/1.1","★☆☆"),@("207","HTTP/2","★★☆"),@("208","HTTP/3","★★★"),@("209","HTTP Methods","★☆☆"),@("210","HTTP Status Codes","★☆☆"),@("211","HTTP Headers","★★☆"),@("212","Keep-Alive / Connection Pooling","★★☆"),@("213","REST","★☆☆"),@("214","RESTful Constraints","★★☆"),@("215","HATEOAS","★★★"),@("216","Idempotency in HTTP","★★☆"),@("217","GraphQL","★★☆"),@("218","GraphQL Schema","★★☆"),@("219","GraphQL Resolvers","★★☆"),@("220","GraphQL N+1 Problem","★★★"),@("221","GraphQL Subscriptions","★★★"),@("222","gRPC","★★☆"),@("223","Protocol Buffers","★★☆"),@("224","gRPC Streaming","★★★"),@("225","SOAP","★★☆"),@("226","WSDL","★★☆"),@("227","WebSocket","★★☆"),@("228","Server-Sent Events (SSE)","★★☆"),@("229","Long Polling","★★☆"),@("230","Webhook","★★☆"),@("231","API Gateway","★★☆"),@("232","API Versioning","★★☆"),@("233","API Rate Limiting","★★☆"),@("234","API Authentication","★★☆"),@("235","OAuth2","★★☆"),@("236","JWT","★★☆"),@("237","OIDC","★★★"),@("238","API Keys","★☆☆"),@("239","HMAC","★★★"),@("240","CORS","★★☆"),@("241","XSS","★★☆"),@("242","CSRF","★★☆"),@("243","SQL Injection","★★☆"),@("244","SSRF","★★★"),@("245","Content Negotiation","★★☆"),@("246","OpenAPI / Swagger","★★☆"),@("247","API Contract Testing","★★★"),@("248","API Mocking","★★☆"),@("249","API Backward Compatibility","★★★"),@("250","BFF (Backend for Frontend)","★★★"),@("251","API Caching","★★☆"),@("252","ETag / Cache-Control","★★★"),@("253","Pagination","★★☆"),@("254","API Throttling","★★☆"),@("255","API Documentation","★☆☆"),@("256","API Design Best Practices","★★☆"),@("257","Hypermedia","★★★"),@("258","API Deprecation Strategy","★★★"),@("259","API Observability","★★★"),@("260","API Security Best Practices","★★★"))
# ── 07 Java JVM (261-310) → update existing ──────────────
Write-Index "Java" "Java & JVM Internals" "java" 7 "261–310" "50 terms" "JVM architecture, memory model, garbage collection algorithms, JIT compilation, GraalVM, and JVM tuning." @(
    @("261","JVM","★☆☆"),@("262","JRE","★☆☆"),@("263","JDK","★☆☆"),@("264","Bytecode","★★☆"),@("265","Class Loader","★★☆"),@("266","Stack Memory","★★☆"),@("267","Heap Memory","★★☆"),@("268","Metaspace","★★☆"),@("269","Stack Frame","★★★"),@("270","Operand Stack","★★★"),@("271","Local Variable Table","★★★"),@("272","Object Header","★★★"),@("273","Escape Analysis","★★★"),@("274","Memory Barrier","★★★"),@("275","Happens-Before","★★★"),@("276","GC Roots","★★★"),@("277","Reference Types (Strong, Soft, Weak, Phantom)","★★★"),@("278","Young Generation","★★☆"),@("279","Eden Space","★★☆"),@("280","Survivor Space","★★☆"),@("281","Old Generation","★★☆"),@("282","Minor GC","★★☆"),@("283","Major GC","★★★"),@("284","Full GC","★★★"),@("285","Stop-The-World (STW)","★★★"),@("286","Serial GC","★★☆"),@("287","Parallel GC","★★☆"),@("288","CMS (Concurrent Mark Sweep)","★★★"),@("289","G1GC","★★★"),@("290","ZGC","★★★"),@("291","Shenandoah GC","★★★"),@("292","GC Tuning","★★★"),@("293","GC Logs","★★☆"),@("294","GC Pause","★★★"),@("295","Throughput vs Latency (GC)","★★★"),@("296","Finalization","★★★"),@("297","JIT Compiler","★★★"),@("298","C1 / C2 Compiler","★★★"),@("299","Tiered Compilation","★★★"),@("300","Method Inlining","★★★"),@("301","Deoptimization","★★★"),@("302","OSR (On-Stack Replacement)","★★★"),@("303","AOT (Ahead-of-Time Compilation)","★★★"),@("304","GraalVM","★★★"),@("305","Native Image","★★★"),@("306","TLAB","★★★"),@("307","Safepoint","★★★"),@("308","Card Table","★★★"),@("309","Write Barrier","★★★"),@("310","Remembered Set","★★★"))
# ── 08 Java Language (311-330) ───────────────────────────
Write-Index "Java Language" "Java Language" "java-language" 8 "311–330" "20 terms" "Java language features: generics, reflection, modern records, sealed classes, pattern matching, and functional APIs." @(
    @("311","String Pool / String Interning","★★☆"),@("312","Autoboxing / Unboxing","★★☆"),@("313","Integer Cache","★★★"),@("314","Generics","★★☆"),@("315","Type Erasure","★★★"),@("316","Bounded Wildcards","★★★"),@("317","Covariance / Contravariance","★★★"),@("318","Varargs","★★☆"),@("319","Reflection","★★★"),@("320","Annotation Processing (APT)","★★★"),@("321","Serialization / Deserialization","★★☆"),@("322","Records (Java 16+)","★★☆"),@("323","Sealed Classes (Java 17+)","★★★"),@("324","Pattern Matching (Java 21+)","★★★"),@("325","invokedynamic","★★★"),@("326","Optional","★★☆"),@("327","Stream API","★★☆"),@("328","Functional Interfaces","★★☆"),@("329","Method References","★★☆"),@("330","Lambda Expressions","★★☆"))
# ── 09 Java Concurrency (331-370) ────────────────────────
Write-Index "Java Concurrency" "Java Concurrency" "java-concurrency" 9 "331–370" "40 terms" "Java threading, synchronization, concurrent data structures, executors, virtual threads, and the Java Memory Model." @(
    @("331","Thread (Java)","★☆☆"),@("332","Runnable","★☆☆"),@("333","Callable","★★☆"),@("334","Future","★★☆"),@("335","CompletableFuture","★★★"),@("336","Thread Lifecycle","★★☆"),@("337","Thread States","★★☆"),@("338","synchronized","★★☆"),@("339","volatile","★★★"),@("340","wait / notify / notifyAll","★★★"),@("341","ReentrantLock","★★★"),@("342","ReadWriteLock","★★★"),@("343","StampedLock","★★★"),@("344","ThreadLocal","★★★"),@("345","Java Memory Model (JMM)","★★★"),@("346","Race Condition","★★☆"),@("347","CAS (Compare-And-Swap)","★★★"),@("348","Optimistic Locking (Java)","★★★"),@("349","Executor","★★☆"),@("350","ExecutorService","★★☆"),@("351","ThreadPoolExecutor","★★★"),@("352","ForkJoinPool","★★★"),@("353","Virtual Threads (Project Loom)","★★★"),@("354","Carrier Thread","★★★"),@("355","Continuation","★★★"),@("356","Semaphore (Java)","★★☆"),@("357","CountDownLatch","★★☆"),@("358","CyclicBarrier","★★★"),@("359","Phaser","★★★"),@("360","BlockingQueue","★★☆"),@("361","ConcurrentHashMap","★★★"),@("362","CopyOnWriteArrayList","★★★"),@("363","Atomic Classes","★★★"),@("364","VarHandle","★★★"),@("365","Structured Concurrency","★★★"),@("366","Scoped Values","★★★"),@("367","Thread Dump Analysis","★★★"),@("368","Deadlock Detection (Java)","★★★"),@("369","Lock Striping","★★★"),@("370","Actor Model","★★★"))
# ── 10 Spring Core (371-410) ─────────────────────────────
Write-Index "Spring" "Spring Core" "spring" 10 "371–410" "40 terms" "Spring IoC/DI, AOP, MVC, data access, transactions, Boot auto-configuration, and reactive programming." @(
    @("371","IoC (Inversion of Control)","★☆☆"),@("372","DI (Dependency Injection)","★☆☆"),@("373","ApplicationContext","★★☆"),@("374","BeanFactory","★★☆"),@("375","Bean","★☆☆"),@("376","Bean Lifecycle","★★☆"),@("377","Bean Scope","★★☆"),@("378","BeanPostProcessor","★★★"),@("379","BeanFactoryPostProcessor","★★★"),@("380","@Autowired","★★☆"),@("381","@Qualifier / @Primary","★★☆"),@("382","@Configuration / @Bean","★★☆"),@("383","Circular Dependency","★★★"),@("384","CGLIB Proxy","★★★"),@("385","JDK Dynamic Proxy","★★★"),@("386","AOP (Aspect-Oriented Programming)","★★☆"),@("387","Aspect","★★☆"),@("388","Advice","★★☆"),@("389","Pointcut","★★☆"),@("390","JoinPoint","★★☆"),@("391","Weaving","★★★"),@("392","DispatcherServlet","★★☆"),@("393","HandlerMapping","★★★"),@("394","Filter vs Interceptor","★★☆"),@("395","@Transactional","★★☆"),@("396","Transaction Propagation","★★★"),@("397","Transaction Isolation Levels","★★★"),@("398","N+1 Problem","★★★"),@("399","Lazy vs Eager Loading","★★☆"),@("400","HikariCP","★★☆"),@("401","Auto-Configuration","★★★"),@("402","Spring Boot Actuator","★★☆"),@("403","Spring Boot Startup Lifecycle","★★★"),@("404","WebFlux / Reactive","★★★"),@("405","Mono / Flux","★★★"),@("406","Backpressure (Spring)","★★★"),@("407","Spring Security","★★★"),@("408","Spring Data JPA","★★☆"),@("409","Spring Cloud","★★★"),@("410","Spring Boot Testing","★★☆"))
Write-Host "Tier 1-4 index files done."